### ISSUE TITLE
Support for version 5

### ISSUE THREAD

**Issue by uzimaru0000** [ricky0123/vad#120]
Hi, thank you for the wonderful library. 
Recently, [silero-vad v5](https://github.com/snakers4/silero-vad/releases/tag/v5.0) was released. Do you have any plans to support it in this library?

I tried downloading and running the v5 model, but an error occurred, so it seems that the source code itself needs to be updated.

```
Unhandled Promise Rejection: Error: input 'state' is missing in 'feeds'.
```

I would appreciate it if you could consider it.

**Comment by arcossci** [comment]
It cold be great if you extend the support for V5, please!

**Comment by ricky0123** [comment]
Hi @arcossci it'll be here soon ;) I have it working but want to take the opportunity to do some reorganizing as well

**Comment by uzimaru0000** [comment]
Hi @ricky0123 how is the support for v5 going?
If there's anything I can help with, I'd like to assist. Thank you.

**Comment by ricky0123** [comment]
Hi all, I released support for v5 and added a [documentation page](https://docs.vad.ricky0123.com/user-guide/silero-v5/) about it. When you upgrade to the newest version, you should also be aware of [this change](https://docs.vad.ricky0123.com/user-guide/browser/#serving-the-workletonnxwasm-files) that affects how you specify where the package looks for the onnx/wasm/worklet files.

You can play with v5 [here](https://test.vad.ricky0123.com/#opts=%7B%22positiveSpeechThreshold%22%3A0.5%2C%22negativeSpeechThreshold%22%3A0.35%2C%22preSpeechPadFrames%22%3A3%2C%22redemptionFrames%22%3A24%2C%22frameSamples%22%3A512%2C%22minSpeechFrames%22%3A9%2C%22submitUserSpeechOnPause%22%3Afalse%2C%22baseAssetPath%22%3A%22https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2F%40ricky0123%2Fvad-web%400.0.20%2Fdist%2F%22%2C%22onnxWASMBasePath%22%3A%22https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fonnxruntime-web%401.14.0%2Fdist%2F%22%2C%22model%22%3A%22v5%22%2C%22startOnLoad%22%3Atrue%2C%22userSpeakingThreshold%22%3A0.6%7D) and try out different parameters.

I am going to wait to get some feedback and also keep searching for a good set of default parameters (redemptionFrames, etc) for v5 before I make it the default.

**Comment by uzimaru0000** [comment]
Thank you for the implementation! I'll start using it right away.
I also appreciate making the playground easier to try out.

Since this issue has been resolved, I’d like to close it.

**Comment by MathiasSoender** [comment]
Hi! Can you give a few tips on how to upgrade to v5?
I have versions:
```
    "@ricky0123/vad-react": "^0.0.27",
    "@ricky0123/vad-web": "^0.0.21",
```
    
Calling the hook, useMicVAD with:
```
useMicVAD({
        ...
        model: `v5`,
    });
```
(Note, I do not specify any of the two paths here)
I get errors in the browser:
![image](https://github.com/user-attachments/assets/94429315-365d-4762-a74d-87bea9486e3d)

I noticed, from the network tab, that my app downloads the following:
silero_vad_v5.onnx
vad.worklet.bundle.min.js
ort-wasm-simd-threaded.wasm

IIRC then these files were also downloaded with previous versions (obv. "_v5" was omitted from the onnx file).

I checked your test site:
https://test.vad.ricky0123.com/

And saw the downloads to be:
silero_vad_v5.onnx
vad.worklet.bundle.min.js
ort-wasm-simd.wasm

I saw that the file sizes are equal for silero_vad_v5.onnx and vad.worklet.bundle.min.js, so I assume that these are equal.

However, ort-wasm-simd.wasm is clearly different from ort-wasm-simd-threaded.wasm. Where do I specify that the useMicVad should use "ort-wasm-simd.wasm" instead of "ort-wasm-simd-threaded.wasm"?

Thanks!

**Comment by ricky0123** [comment]
Hi @MathiasSoender from your edit it looks like your problem is solved. Let me know if you have any other issues
