### ISSUE TITLE
Feature Request: Send audio frame in onFrameProcessed callback

### ISSUE THREAD

**Issue by patconrey** [ricky0123/vad#13]
I'm using this as a VAD in an audio streaming application. I only want to stream audio frames that have speech in them. Since I'm streaming in realtime, I'm wondering if it's possible to get the audio frame that was processed via `onFrameProcessed`? I believe this would require three things: (1) updating the [function signature](https://github.com/ricky0123/vad/blob/master/packages/web/src/real-time-vad.ts#L53) of `onFrameProcessed`; (2) passing `audio` into the `onFrameProcessed` callback [here](https://github.com/ricky0123/vad/blob/master/packages/web/src/real-time-vad.ts#L147); and (3) returning `frame` by default in the `process` function [here](https://github.com/ricky0123/vad/blob/master/packages/_common/src/frame-processor.ts#L215) (e.g., `return { probs, audio: frame }`).

I imagine that this _could_ have performance costs, as passing a 1536-length Float32Array every ~0.1 seconds seems like it would be expensive in aggregate.

Alternatively, I'm curious if you think there's a better way to handle this by maybe introducing a secondary audio processor node that could receive audio frames classified as speech?

Thank you so much for your help!

**Comment by ricky0123** [comment]
Hey Pat, my first thought is that it may be better to write your own solution for streaming, and then use the voice activity detector to toggle whether streaming is turned on or off. Something like

```typescript
const streamingConnection = myStreamingSolution()
const myvad = await MicVAD.new({
    onSpeechStart: () => {
        streamingConnection.start()
    },
    onVADMisfire: () => {
        streamingConnection.pause()
    },
    onSpeechEnd: () => {
        streamingConnection.pause()
    },
})
myvad.start()
```

I'm not sure if you want to ultimately send the audio to other users so that users can have real-time audio communcation or if you want to send the audio to the server for further processing. But this solution would allow you to use the [WebRTC API](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API) for the streaming portion of it, which would be more performant and simpler if you are trying to send the audio to other users in order to hear in real time. You may run into latency issues if you try to send each raw audio frame to your server/other users.

Alternatively, if you do want to access the speech frames in real time, one way to do it would be to create another audio worklet that passes the audio frames to the main process (see [here](https://github.com/ricky0123/vad/blob/5c581188e0a4d7e9f0d2dcedce01cacb4e0949f7/packages/web/src/real-time-vad.ts#L188), [here](https://github.com/ricky0123/vad/blob/5c581188e0a4d7e9f0d2dcedce01cacb4e0949f7/packages/web/src/worklet.ts#L37)), and again use the VAD as a "toggle" as I demonstrated above.

If these options don't work, we could definitely talk about one of the other solutions you mentioned.

Also, it's worth pointing out that all of these solutions will probably fail to stream the very beginning of speech segments. When you do all of the audio processing using the `onSpeechEnd` callback, it prepends `preSpeechPadFrames` of audio to the segment, which usually contains a small amount of speech. There's no way to stream that in real time. It may or may not be an issue for you.

**Comment by dongzeli95** [comment]
> Also, it's worth pointing out that all of these solutions will probably fail to stream the very beginning of speech segments. When you do all of the audio processing using the `onSpeechEnd` callback, it prepends `preSpeechPadFrames` of audio to the segment, which usually contains a small amount of speech. There's no way to stream that in real time. It may or may not be an issue for you.

Thank you for making this suggestion. I am currently using this vad in conjunction with a media recorder to stream audio bytes to our backend server. However I realize there is always a 1-second cutoff at the very beginning of the speech if I just simply start the recorder whenever onSpeechStart get called. Is there a way to mitigate this? Would using `preSpeechPadFrames` help in this case? Thank you so much 🙏
