### ISSUE TITLE
[QUESTION] Clarification on ONNX Model Version and Custom Model Support

### ISSUE THREAD

**Issue by ihorkozar** [ricky0123/vad#151]
It looks like you added the ONNX model to this repository about two years ago, but I don’t see which version of the model is currently being used. Could you tell me the version, or perhaps let me know if it’s possible to use my own ONNX model instead?

**Comment by ricky0123** [comment]
Hi @ihorkozar I don't remember what version, but can you tell me more about the model you have? Is it a fine-tuned version of one of the Silero models?

**Comment by ihorkozar** [comment]
@ricky0123 The official repository has release versions and the latest version is v5.1 https://github.com/snakers4/silero-vad/releases

**Comment by ricky0123** [comment]
I see, so you are just interested in using a newer official silero model. I am working on support for that now. You can track progress [here](https://github.com/ricky0123/vad/pull/154). It will probably be released next week. Unfortunately it is not as simple as replacing the model file because the newer model is structured slightly differently, requires a different frame size, etc
