### ISSUE TITLE
Server Error SyntaxError: Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by taiyop** [ricky0123/vad#18]
I'm using this lib with Next.js.
So I tried to use package of 'vad-react' and I had the followings error.

```
 Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Call Stack
unknown
node_modules/ (ricky0123/vad-react/dist/index.js (1)
```

The following is my code.

```
import { useMicVAD, utils as utilsVAD } from "@ricky0123/vad-react"
...
const micVAD = useMicVAD(micVADOption)
```

**Comment by ricky0123** [comment]
Okay, thanks for letting me know. I will look into it. In the meantime, for a temporary solution, I suspect it might work if you change the import to 
```typescript
import { useMicVAD, utils as utilsVAD } from "@ricky0123/vad-react/dist/bundle.min.js"
```

**Comment by ricky0123** [comment]
Also, you will have to make sure this code runs in the browser, not on the server.

**Comment by DamienDabernat** [comment]
Hello @ricky0123 thanks for this great project.

I am not a great web expert and I also have some difficulties to use this project with Next.js.

I don't know if the configuration of `nuxt.config.ts` is correct too.

I don't necessarily have the same errors as @taiyop. But, for example, I can't find a "bundle.min.js" file in "@ricky0123/vad-react/dist/bundle.min.js" should I just rename "vad.worklet.bundle.min.js"?

I can help create a sample project in Next.js if I can figure out where the errors are coming from.

**Comment by ricky0123** [comment]
Okay, I'm happy to say I finally got this working. There's an example [here](https://github.com/ricky0123/vad/tree/master/examples/nextjs). Just add the required stuff to `next.config.js` and wrap the component that uses the VAD in the nextjs `dynamic` function as demonstrated in the example.

There's one issue though - the vad doesn't behave properly when using the Nextjs development server. I think this may have something to do with [react strict mode](https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode) being enabled for the dev server, but I haven't checked to see if it works when react strict mode is disabled. The issue is that it seems to create two voice activity detectors. But from my quick test, the vad seems to work when using `npm run build && npm run start`.

Let me know if you run into any other issues.
