### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by olzhasmukayev** [ricky0123/vad#76]
Hi! 

Can I use this library in React Native application?

**Comment by ricky0123** [comment]
Hi @olzhasmukayev , thanks for your question. I have never used React Native, but I don't think this package will work out of the box for you due to making use of a browser api called the web audio api that is not available to native android/ios apps. There may be partial workarounds such as polyfills (although a quick search did not turn up any), packaging your app such that it runs on a browser instead of as a native app, or using an embedded "web view", but that is just speculation. Feel free to share anything you find in this thread
